
VariableTracker.fileMenu.text=File
VariableTracker.editMenu.text=Edit
VariableTracker.helpMenu.text=Help
VariableTracker.infoMenuItem.text=Info
VariableTracker.openMenuItem.text=Open
VariableTracker.saveMenuItem.text=Save
VariableTracker.optionsButton.text=Options
VariableTracker.hideTempVarButton.text=Hide Temp Vars
VariableTracker.searchLabel.text=Search\: 
VariableTracker.selectedLabel.text=Selected\:
VariableTracker.variablesLabel.text=Variables
VariableTracker.variableDescriptionLabel.text=Variable Description
VariableTracker.variableTable.varHex=Hex
VariableTracker.variableTable.varDecimal=Decimal
VariableTracker.variableTable.varName=Name

VariableTracker.variableValuesTable.value=Value
VariableTracker.variableValuesTable.valueName=Name
VariableTracker.variableValuesTable.valueDescription=Description

variableTable.popUp.removeItem.text=Remove entry
variableTable.popUp.addItem.text=Add new entry
variableTable.popUp.copyNameItem.text=Copy variable name

variableTable.addDialog.prompt.text=What is the variable value?\n(You may use hex or decimal).
variableTable.addDialog.idConflict.text=An entry for this variable already exists. Action aborted.
variableTable.addDialog.invalidNumber.text=This is not a valid number. Action aborted.
errorTitle.text=Error

variableTable.removeItem.tempVarRemovalFailure.text=This variable cannot be removed.

VariableTracker.infoDialog.text=Variables are used to track progression for scripts and triggers, and also are used as temporary storage in memory during script execution.\n\nVariables in the 0x4000-0x401F range are temporary local variables that reset upon leaving the current header/map.\n\nVariables in the 0x8000 to 0x800C range are temporary and reset upon the end of the current script.\n\nYou can freely use variables from 0x4020 through 0x411F (I think).